### PR TITLE
STDIN greater than 64KB fix

### PR DESCRIPTION
**Pull request by nicklozon**
I ran into issues when publishing messages from a text file greater than 64KB.

React Stream has a 65536 byte buffer size which means the `data` event will trigger multiple times for files larger than 64KB. This caused the messages that occur at each 64KB mark to be split in half and published as two separate messages. This PR addresses multiple `data` events by temporarily holding the last message of a `data` event over to the next, then listening for the `end` event to publish the last one.

This solution is working fine, but I am concerned about race conditions by using closure with the `$previousMessage` variable for temporary storage between `data` events.

Additional notes:
- `trim()` calls should occur prior to publishing when it is certain that the message is intact or else it could result in trimming white-space int he middle of the message.
- `$once` has been added to the `end` event callable

### CODE REVIEW

**Comment by cboden** [comment]
Thanks for the PR. I'll be able to test this in about 2 weeks. 

Off the top of my head I think moving the `$once` call to end will break this use case:
`cat myScaffoldingFile | binky -w amq.topic:myKey -o`

If I remember correctly, the `php://stdin` stream does not end, which is why I think I added the `-o` flag.

**Comment by nicklozon** [comment]
No problem! You'll probably want to re-do the code style, I just hacked it together to fix the issue.

I have been using `-o` and the `end` event has been firing successfully running on my Mac.

**Comment by cboden** [comment]
Reviewing/testing now. If what you say is true that might make the `-o` flag redundant, which would be nice to remove.

**Review by cboden — APPROVED** [review]
I merged it, but GitHub hasn't recognized it...

**Pull request closed without merging**
